"""add hero_enabled and best_sellers_enabled to site_settings

Revision ID: 39a200e8a9af
Revises: 93c6fd644e5f
Create Date: 2026-09-07 06:28:21.575597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a200e8a9af'
down_revision: Union[str, Sequence[str], None] = '93c6fd644e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hero_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('site_settings', sa.Column('best_sellers_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'best_sellers_enabled')
    op.drop_column('site_settings', 'hero_enabled')
    # ### end Alembic commands ###
