"""add product is_featured and site_settings table

Revision ID: 4f8a544de0aa
Revises: 1dc3954a1979
Create Date: 2026-09-04 08:01:54.683462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8a544de0aa'
down_revision: Union[str, Sequence[str], None] = '1dc3954a1979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('hero_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('about_heading', sa.String(length=255), nullable=True),
    sa.Column('about_body', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'products',
        sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('products', 'is_featured', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
