"""add video url to products

Revision ID: 5b60719b25c1
Revises: 068cd02579b3
Create Date: 2026-09-18 04:51:34.827863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b60719b25c1'
down_revision: Union[str, Sequence[str], None] = '068cd02579b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('video_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('video_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'video_public_id')
    op.drop_column('products', 'video_url')
    # ### end Alembic commands ###
