"""add extra image urls to products

Revision ID: 93c6fd644e5f
Revises: cfe2c66f0bfc
Create Date: 2026-09-04 08:37:59.692738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93c6fd644e5f'
down_revision: Union[str, Sequence[str], None] = 'cfe2c66f0bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('extra_image_urls', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('products', sa.Column('extra_image_public_ids', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'extra_image_public_ids')
    op.drop_column('products', 'extra_image_urls')
    # ### end Alembic commands ###
