"""add hero heading and subheading to site_settings

Revision ID: cfe2c66f0bfc
Revises: 4f8a544de0aa
Create Date: 2026-09-04 08:12:15.780080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe2c66f0bfc'
down_revision: Union[str, Sequence[str], None] = '4f8a544de0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hero_heading', sa.String(length=255), nullable=True))
    op.add_column('site_settings', sa.Column('hero_subheading', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'hero_subheading')
    op.drop_column('site_settings', 'hero_heading')
    # ### end Alembic commands ###
