"""add hero_slides and carousels tables, trim site_settings

Revision ID: fc5dc5264822
Revises: 39a200e8a9af
Create Date: 2026-09-07 06:54:51.751620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5dc5264822'
down_revision: Union[str, Sequence[str], None] = '39a200e8a9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousels_id'), 'carousels', ['id'], unique=False)
    op.create_table('hero_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('subheading', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_slides_id'), 'hero_slides', ['id'], unique=False)

    # --- Data migration: carry the old singleton hero/best-sellers content
    # into the new multi-row tables before their source columns are dropped. ---
    bind = op.get_bind()

    old_hero = bind.execute(sa.text(
        "SELECT hero_image_url, hero_image_public_id, hero_heading, "
        "hero_subheading, hero_enabled FROM site_settings WHERE id = 1"
    )).mappings().first()

    if old_hero and old_hero["hero_image_url"]:
        bind.execute(
            sa.text(
                "INSERT INTO hero_slides "
                "(image_url, image_public_id, heading, subheading, is_active, sort_order) "
                "VALUES (:image_url, :image_public_id, :heading, :subheading, :is_active, 0)"
            ),
            {
                "image_url": old_hero["hero_image_url"],
                "image_public_id": old_hero["hero_image_public_id"],
                "heading": old_hero["hero_heading"],
                "subheading": old_hero["hero_subheading"],
                "is_active": old_hero["hero_enabled"],
            },
        )

    old_best_sellers_enabled = bind.execute(
        sa.text("SELECT best_sellers_enabled FROM site_settings WHERE id = 1")
    ).scalar()

    featured_ids = [
        row[0]
        for row in bind.execute(
            sa.text(
                "SELECT id FROM products WHERE is_featured = true ORDER BY created_at DESC"
            )
        ).fetchall()
    ]

    # Built as a literal array from ids we just queried ourselves (trusted
    # integers, not user input) since ARRAY binding through a raw text()
    # param isn't reliable across drivers.
    product_ids_sql = (
        "ARRAY[" + ",".join(str(pid) for pid in featured_ids) + "]::integer[]"
        if featured_ids
        else "NULL"
    )
    bind.execute(
        sa.text(
            "INSERT INTO carousels (title, is_active, sort_order, product_ids) "
            f"VALUES ('Best Sellers', :is_active, 0, {product_ids_sql})"
        ),
        {
            "is_active": bool(old_best_sellers_enabled) if old_best_sellers_enabled is not None else True,
        },
    )

    op.drop_column('site_settings', 'best_sellers_enabled')
    op.drop_column('site_settings', 'hero_image_public_id')
    op.drop_column('site_settings', 'hero_heading')
    op.drop_column('site_settings', 'hero_subheading')
    op.drop_column('site_settings', 'hero_image_url')
    op.drop_column('site_settings', 'hero_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hero_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('site_settings', sa.Column('hero_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site_settings', sa.Column('hero_subheading', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site_settings', sa.Column('hero_heading', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site_settings', sa.Column('hero_image_public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site_settings', sa.Column('best_sellers_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_hero_slides_id'), table_name='hero_slides')
    op.drop_table('hero_slides')
    op.drop_index(op.f('ix_carousels_id'), table_name='carousels')
    op.drop_table('carousels')
    # ### end Alembic commands ###
